// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: proto/cmgrep.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrepCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IgnoreCase    bool                   `protobuf:"varint,2,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	Extended      bool                   `protobuf:"varint,3,opt,name=extended,proto3" json:"extended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepCountRequest) Reset() {
	*x = GrepCountRequest{}
	mi := &file_proto_cmgrep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepCountRequest) ProtoMessage() {}

func (x *GrepCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmgrep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepCountRequest.ProtoReflect.Descriptor instead.
func (*GrepCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmgrep_proto_rawDescGZIP(), []int{0}
}

func (x *GrepCountRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepCountRequest) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *GrepCountRequest) GetExtended() bool {
	if x != nil {
		return x.Extended
	}
	return false
}

type GrepCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepCountResponse) Reset() {
	*x = GrepCountResponse{}
	mi := &file_proto_cmgrep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepCountResponse) ProtoMessage() {}

func (x *GrepCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmgrep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepCountResponse.ProtoReflect.Descriptor instead.
func (*GrepCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmgrep_proto_rawDescGZIP(), []int{1}
}

func (x *GrepCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_cmgrep_proto protoreflect.FileDescriptor

const file_proto_cmgrep_proto_rawDesc = "" +
	"\n" +
	"\x12proto/cmgrep.proto\x12\x06cmgrep\"i\n" +
	"\x10GrepCountRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1f\n" +
	"\vignore_case\x18\x02 \x01(\bR\n" +
	"ignoreCase\x12\x1a\n" +
	"\bextended\x18\x03 \x01(\bR\bextended\")\n" +
	"\x11GrepCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2J\n" +
	"\x06Cmgrep\x12@\n" +
	"\tGrepCount\x12\x18.cmgrep.GrepCountRequest\x1a\x19.cmgrep.GrepCountResponseB\x1eZ\x1cgithub.com/maxh/cmgrep/protob\x06proto3"

var (
	file_proto_cmgrep_proto_rawDescOnce sync.Once
	file_proto_cmgrep_proto_rawDescData []byte
)

func file_proto_cmgrep_proto_rawDescGZIP() []byte {
	file_proto_cmgrep_proto_rawDescOnce.Do(func() {
		file_proto_cmgrep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cmgrep_proto_rawDesc), len(file_proto_cmgrep_proto_rawDesc)))
	})
	return file_proto_cmgrep_proto_rawDescData
}

var file_proto_cmgrep_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cmgrep_proto_goTypes = []any{
	(*GrepCountRequest)(nil),  // 0: cmgrep.GrepCountRequest
	(*GrepCountResponse)(nil), // 1: cmgrep.GrepCountResponse
}
var file_proto_cmgrep_proto_depIdxs = []int32{
	0, // 0: cmgrep.Cmgrep.GrepCount:input_type -> cmgrep.GrepCountRequest
	1, // 1: cmgrep.Cmgrep.GrepCount:output_type -> cmgrep.GrepCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cmgrep_proto_init() }
func file_proto_cmgrep_proto_init() {
	if File_proto_cmgrep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cmgrep_proto_rawDesc), len(file_proto_cmgrep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cmgrep_proto_goTypes,
		DependencyIndexes: file_proto_cmgrep_proto_depIdxs,
		MessageInfos:      file_proto_cmgrep_proto_msgTypes,
	}.Build()
	File_proto_cmgrep_proto = out.File
	file_proto_cmgrep_proto_goTypes = nil
	file_proto_cmgrep_proto_depIdxs = nil
}
